application: guevonaso
version: 1
runtime: python
api_version: 1

handlers:
 
- url: /(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))
- url: /(.*\.(js))
  static_files: static/javascript/\1
  upload: static/javascript(.*\.(js))
- url: /(.*\.(css))
  static_files: static/\1
  upload: static/(.*\.(css))
- url: /.*
  script: guevonaso_main.py
